name: Deploy Astro site to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🧠 Handles install + build + upload automatically
      - name: Build with Astro
        uses: withastro/action@v4
        with:
          node-version: 20  # optional
          # path: .  # only needed if your astro project isn’t at the repo root

      # 🚀 Deploy the built artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
